language: cpp
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc6-dev-amd64
env:
  matrix:
    - BSL_LIBRARY=static_library BSL_ABI=32 BSL_SAFE=0 BUILDTYPE=Release
    - BSL_LIBRARY=static_library BSL_ABI=32 BSL_SAFE=0 BUILDTYPE=Debug
    - BSL_LIBRARY=static_library BSL_ABI=32 BSL_SAFE=1 BUILDTYPE=Release
    - BSL_LIBRARY=static_library BSL_ABI=32 BSL_SAFE=1 BUILDTYPE=Debug
    - BSL_LIBRARY=shared_library BSL_ABI=32 BSL_SAFE=0 BUILDTYPE=Release
    - BSL_LIBRARY=shared_library BSL_ABI=32 BSL_SAFE=0 BUILDTYPE=Debug
    - BSL_LIBRARY=shared_library BSL_ABI=32 BSL_SAFE=1 BUILDTYPE=Release
    - BSL_LIBRARY=shared_library BSL_ABI=32 BSL_SAFE=1 BUILDTYPE=Debug
before_script:
  - "python ./tools/bde_gyp.py -D library=$BSL_LIBRARY -D ABI_bits=$BSL_ABI -D dbg_safe=$BSL_SAFE"
script:
  - "make -C build all"
branches:
  only:
    - master
